trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: GITHUB_PAT  # Reference your variable group here
  - name: REPO_DIR
    value: $(Build.SourcesDirectory)/Hexagon-_Tasks

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "##[section]Cloning Repository"
    git clone https://$(GITHUB_PAT)@github.com/Anish-blip/Hexagon-_Tasks.git $(REPO_DIR)
  displayName: 'Clone GitHub Repository'

- script: |
    echo "##[section]Installing Dependencies"
    pip install -r $(REPO_DIR)/requirements.txt || true  # Modify this line to point to your requirements file if needed
  displayName: 'Install Dependencies'

- script: |
    echo "##[section]Running Python Scripts"
    cd $(REPO_DIR)
    ls -l  # List the files in the repository for debugging
    for file in *.py; do
      if [[ "$file" == "reverse_number.py" ]]; then
        echo "Running $file with argument 12345"
        python "$file" 12345 > "$(Build.ArtifactStagingDirectory)/output_${file%.py}.txt" 2>&1 || { echo "Failed to run $file"; cat "$(Build.ArtifactStagingDirectory)/output_${file%.py}.txt"; exit 1; }
      elif [[ "$file" == "sum.py" ]]; then
        echo "Running $file with argument 1234"
        python "$file" 1234 > "$(Build.ArtifactStagingDirectory)/output_${file%.py}.txt" 2>&1 || { echo "Failed to run $file"; cat "$(Build.ArtifactStagingDirectory)/output_${file%.py}.txt"; exit 1; }
      else
        echo "Running $file"
        python "$file" > "$(Build.ArtifactStagingDirectory)/output_${file%.py}.txt