trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubAuthentication  # Reference to your variable group containing GITHUB_TOKEN

steps:
- checkout: self
  displayName: 'Checkout GitHub Repository'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    for file in *.py; do
        python "$file" > "${file%.py}_output.txt"
    done
  displayName: 'Run Python Scripts and Gather Outputs'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "anishanish24402@gmail.com"
      git config --global user.name "Anish-blip"
      git remote set-url origin https://anishanish24402:$(GITHUB_TOKEN)@github.com/Anish-blip/Hexagon-_Tasks.git
      git checkout -b main origin/main
      git pull origin main
      git add *_output.txt
      git commit -m "Add script outputs"
      git push origin main
  displayName: 'Push Output Files to GitHub'
