trigger:
- python_task

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Running Python script..."
    python reverse_number.py > output.txt
    echo "Exit code: $?"
    cat output.txt
  displayName: 'Run Python script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'output.txt'
    artifact: 'output'
    publishLocation: 'pipeline'

- script: |
    git config --global user.name 'Anish-blip'
    git config --global user.email 'anishanish24402@gmail.com'
    git fetch origin python_task
    git checkout python_task
    git pull origin python_task
    git add output.txt
    git commit -m "Add script output"
    git push origin python_task
  displayName: 'Push output to GitHub'
