
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubAuthentication  # Reference to your variable group containing GITHUB_TOKEN

steps:
- checkout: self
  displayName: 'Checkout GitHub Repository'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    for file in *.py; do
        python "$file" > "${file%.py}_output.txt"
    done
    ls -la  # List files to verify output files are created
  displayName: 'Run Python Scripts and Gather Outputs'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Configuring Git..."
      git config --global user.email "anishanish24402@gmail.com"
      git config --global user.name "Anish-blip"
      git remote set-url origin https://anishanish24402:$(GITHUB_TOKEN)@github.com/Anish-blip/Hexagon-_Tasks.git
      echo "Fetching and checking out the main branch..."
      git fetch origin main
      git checkout main
      git pull origin main
      echo "Adding and committing output files..."
      git add *_output.txt
      git commit -m "Add script outputs"
      echo "Pushing changes to GitHub..."
      git push https://anishanish24402:$(GITHUB_TOKEN)@github.com/Anish-blip/Hexagon-_Tasks.git main
  displayName: 'Push Output Files to GitHub'
