trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "##[section]Cloning Repository"
    git clone https://$(GITHUB_PAT)@github.com/Anish-blip/Hexagon-_Tasks.git
  displayName: 'Clone GitHub Repository'
  env:
    GITHUB_PAT: $(GITHUB_PAT)

- script: |
    echo "##[section]Running Python Scripts"
    cd Hexagon-_Tasks
    ls -l  # List the files in the repository for debugging
    python volume.py > output.txt  # Run the Python script and redirect output to output.txt
    echo "##[section]After running Python script"
    ls -l  # List the files again to verify if output.txt was created
  displayName: 'Run Python Scripts'

- script: |
    echo "##[section]Gathering Results"
    cp Hexagon-_Tasks/output.txt $(Build.ArtifactStagingDirectory)/
  displayName: 'Gather Results'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/output.txt'
    artifactName: 'output'
    publishLocation: 'Container'

- script: |
    echo "##[section]Pushing Results to GitHub"
    cd Hexagon-_Tasks
    git config --global user.name "Anish-blip"
    git config --global user.email "your-email@example.com"
    git add output.txt
    git commit -m "Add script output"
    git push https://$(GITHUB_PAT)@github.com/Anish-blip/Hexagon-_Tasks.git
  displayName: 'Push Results to GitHub'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
