trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      echo "##[section]Cloning Repository"
      git clone https://$GITHUB_PAT@github.com/Anish-blip/Hexagon-_Tasks.git
      ls -l  # List files after clone for debugging
    displayName: 'Clone GitHub Repository'
    env:
      GITHUB_PAT: $(GITHUB_PAT)

  - script: |
      echo "##[section]Debug: Listing Python Files in Repository"
      cd Hexagon-_Tasks
      ls -l *.py || echo "No Python files found!"
    displayName: 'Debug: List Python Files'

  - script: |
      echo "##[section]Running Python Scripts"
    
