---
- name: Reverse a number using Python script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Copy Python script to localhost
      copy:
        src: reverse_number.py
        dest: /tmp/reverse_number.py
        mode: '0755'

    - name: Execute the Python script with number 1234
      command: /tmp/reverse_number.py 1234
      register: script_output

    - name: Display the output of the script
      debug:
        msg: "{{ script_output.stdout }}"

